"""Constructs the corpora cannot reach, pinned against the pure-Python extractor.

`harness/kernel_walker_parity.py` and `harness/kernel_python_e2e_parity.py` compare
the native Python walker against `_extract_generic` / `extract_python` over 3,283
real files, which is the primary evidence. But a corpus only exercises what it
happens to contain, and an injection sweep found one branch it cannot reach at all:
django has 165 auto-generated files and NOT ONE of them has a module docstring long
enough to emit, so disabling `_is_autogenerated_python` in the kernel changed
nothing and the parity run passed. A branch that no corpus can reach needs a test
or it is not covered, whatever the file count says.

Each test compares the two implementations on one source. `GRAPHIFY_KERNEL` is read
once at import, so the arms are switched by calling the walker directly rather than
by re-importing.
"""
from __future__ import annotations

import contextlib
import json

import pytest

from graphify.extract import _PYTHON_CONFIG, extract_python
from graphify.extractors import kernel as kseam
from graphify.extractors.engine import _extract_generic

kernel = pytest.importorskip("graphify_kernel", reason="native kernel not built")


def _canon(o) -> str:
    return json.dumps(o, sort_keys=True, ensure_ascii=False,
                      separators=(",", ":"), default=str)


@contextlib.contextmanager
def _seam_disabled():
    """Make `_extract_generic` take the pure-Python path for the control arm.

    Without this the control IS the kernel: `_extract_generic` calls
    `kernel.try_extract` at its top, so once `python` is in `supported_languages()`
    both arms are native and every test passes vacuously. Caught here by tests that
    failed for an unrelated-looking reason; the same trap is documented at point (1)
    of `harness/kernel_walker_parity.py`.
    """
    original = kseam.try_extract
    kseam.try_extract = lambda *a, **kw: None
    try:
        yield
    finally:
        kseam.try_extract = original


def _both(tmp_path, source: str, name: str = "m.py"):
    """(native, python) results for one source, as `extract_python` would produce.

    The Python arm is built by hand rather than by toggling `GRAPHIFY_KERNEL`: the
    kernel's load state is cached for the process, so a test that flipped the env
    var would depend on import order.
    """
    p = tmp_path / name
    p.write_text(source)
    native, reason = kernel.extract_file(
        str(p), p.read_bytes(), "python",
        kseam._import_resolver(str(p)), kseam._module_resolver(str(p)),
        kseam._py_import_resolver(str(p)),
    )
    assert native is not None, f"kernel deferred ({reason}); this test proves nothing"
    # Mirror extract_python's tail so rationale nodes are included on both sides.
    from graphify.extract import _apply_python_rationale_native, _extract_python_rationale
    items = native.pop("py_rationale", None)
    assert items is not None, "rationale payload deferred; this test proves nothing"
    _apply_python_rationale_native(p, native, items)
    # Raw material for phase 3's cross-file pass, consumed in the parent and never
    # part of the graph. The control arm has no counterpart; `_xfile_both` below
    # compares it where it matters, at that pass's boundary.
    native.pop("py_xfile", None)
    native.pop("py_symbol_facts", None)

    with _seam_disabled():
        py = _extract_generic(p, _PYTHON_CONFIG)
        _extract_python_rationale(p, py, None)
    return native, py


AUTOGENERATED_WITH_DOCSTRING = '''\
"""This module holds the revision identifiers used by the migration runner."""
# DO NOT EDIT

revision = "a1b2c3"
down_revision = "000000"


def upgrade():
    """Apply the schema change described by this revision identifier."""
    pass
'''


def test_autogenerated_module_docstring_is_suppressed(tmp_path):
    """The branch no corpus reaches: auto-generated AND a long module docstring.

    `_is_autogenerated_python` must suppress the MODULE docstring (a revision
    annotation, not rationale) while leaving the function docstring alone. Getting
    this wrong adds a rationale node to every generated file in a repo.
    """
    native, py = _both(tmp_path, AUTOGENERATED_WITH_DOCSTRING)
    assert _canon(native) == _canon(py)
    labels = [n["label"] for n in native["nodes"] if n.get("file_type") == "rationale"]
    assert any("Apply the schema change" in l for l in labels), (
        "the function docstring should still be emitted; if it is not, this test "
        "would pass even with the suppression removed"
    )
    assert not any("revision identifiers" in l for l in labels), (
        "the module docstring of an auto-generated file must be suppressed"
    )


@pytest.mark.parametrize("marker", [
    '"""Doc."""\n# DO NOT EDIT\n',
    '"""Doc."""\n# @generated by something\n',
    '"""Doc."""\n# Generated by the protocol buffer compiler.\n',
    '"""Doc."""\nclass Migration(migrations.Migration):\n    operations = []\n',
])
def test_each_autogenerated_marker_agrees(tmp_path, marker):
    """One case per marker in `_is_autogenerated_python`, since they are separate
    conditions and a single fixture would leave three of them untested."""
    source = (
        '"""A module docstring long enough to clear the twenty-character gate."""\n'
        + marker.split("\n", 1)[1]
    )
    native, py = _both(tmp_path, source)
    assert _canon(native) == _canon(py)


def test_docstring_exactly_at_the_length_gate(tmp_path):
    """`len(text) > 20` counts CHARACTERS. A 20-char docstring is NOT emitted and a
    21-char one is; an off-by-one here silently changes every borderline file."""
    for n, expect in ((20, False), (21, True)):
        native, py = _both(tmp_path, f'"""{"x" * n}"""\n', name=f"g{n}.py")
        assert _canon(native) == _canon(py)
        got = any(x.get("file_type") == "rationale" for x in native["nodes"])
        assert got is expect, f"{n} chars: emitted={got}, expected {expect}"


def test_non_ascii_docstring_body(tmp_path):
    """The id recipe defers on non-ASCII, but a docstring's TEXT is only ever a
    label -- it must not defer, and the label is built by the same Python helper on
    both paths."""
    native, py = _both(tmp_path, '"""Ünïcödé rationale text that is quite long."""\n')
    assert _canon(native) == _canon(py)


def test_form_feed_defers_the_rationale_payload_only(tmp_path):
    """A form feed is a `str.splitlines()` break that Rust's `.lines()` misses, so
    every rationale line number after it would shift. The payload must defer -- and
    the nodes/edges must still come from the kernel, since the two are separate
    axes."""
    p = tmp_path / "ff.py"
    p.write_text('def a():\n    pass\n\x0c\n# NOTE: after the page break\n')
    native, reason = kernel.extract_file(
        str(p), p.read_bytes(), "python",
        kseam._import_resolver(str(p)), kseam._module_resolver(str(p)),
        kseam._py_import_resolver(str(p)),
    )
    assert native is not None, f"the whole file must not defer, only its rationale ({reason})"
    assert "py_rationale" not in native, "the rationale payload must defer on a form feed"
    # And the end-to-end result must still match, via the Python fallback.
    got = extract_python(p)
    # phase-3 raw material; the control arm has no counterpart
    got.pop("py_xfile", None)
    got.pop("py_symbol_facts", None)
    assert _canon(got) == _canon(_fallback(p))


def _fallback(p):
    from graphify.extract import _extract_python_rationale
    with _seam_disabled():
        py = _extract_generic(p, _PYTHON_CONFIG)
        _extract_python_rationale(p, py, None)
    return py


def test_relative_import_resolution_matches(tmp_path):
    """The relative-import branch is the one place the walker calls back into
    Python, and it decides an edge TARGET. A package directory must resolve to its
    `__init__.py`, not to a nonexistent `pkg.py` (#2455)."""
    (tmp_path / "pkg").mkdir()
    (tmp_path / "pkg" / "__init__.py").write_text("value = 1\n")
    native, py = _both(tmp_path, "from .pkg import value\nfrom .missing import other\n")
    assert _canon(native) == _canon(py)
    targets = {e["target"]: e for e in native["edges"] if e["relation"] == "imports_from"}
    assert any("target_file" in e for e in targets.values()), (
        "the resolvable import should be stamped with its target file"
    )
    assert any("target_file" not in e for e in targets.values()), (
        "the unresolvable one must stay dangling, not be stamped speculatively"
    )


# ── cross-file import fusion (`py_xfile`) ────────────────────────────────────
#
# `_resolve_cross_file_imports` is compared here at the PASS boundary: the same
# per-file results, once with the kernel's payload and once with it stripped so
# the original parse-and-walk path runs. The whole-graph gate
# (`harness/kernel_graph_ab.py`) covers what this cannot -- a payload that goes
# stale before phase 3 reads it -- and these cover what the corpora cannot reach.

def _xfile_both(tmp_path, files: dict[str, str]):
    """(native, python) edge lists from `_resolve_cross_file_imports`."""
    from graphify.extractors.resolution import _resolve_cross_file_imports

    paths = []
    for name, body in files.items():
        p = tmp_path / name
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(body)
        paths.append(p)

    per_file = [extract_python(p) for p in paths]
    assert any("py_xfile" in r for r in per_file), (
        "no file produced a py_xfile payload; this test proves nothing"
    )
    native = _resolve_cross_file_imports(per_file, paths)
    stripped = [{k: v for k, v in r.items() if k != "py_xfile"} for r in per_file]
    with _seam_disabled():
        py = _resolve_cross_file_imports(stripped, paths)
    return native, py


def test_module_name_falls_through_to_the_imported_name(tmp_path):
    """The quirk django cannot reach: `resolve_import`'s loop keeps trying LATER
    `dotted_name` children when an earlier one does not resolve.

    The imported names are themselves direct `dotted_name` children, and the
    secondary index is keyed by FILE stem -- so `from unknownmod import Client`,
    with no `unknownmod` in the index but a `Client.py` present, resolves the
    import target to `Client.py`. Surprising, but it is the behaviour, and a
    walker that emitted only the first candidate would silently drop the edge.
    Injecting exactly that simplification changed NOTHING on django's 2,929
    files, which is why this test exists.
    """
    native, py = _xfile_both(tmp_path, {
        "Client.py": "class Client:\n    pass\n",
        "user.py": (
            "from unknownmod import Client\n"
            "class Service:\n"
            "    def go(self):\n"
            "        return Client()\n"
        ),
    })
    assert _canon(native) == _canon(py)
    assert native, (
        "the fall-through produced no edge at all, so this test would pass even "
        "with the fall-through removed"
    )


def test_relative_import_wins_over_an_earlier_candidate(tmp_path):
    """A `relative_import` stops the scan and overrides any candidate collected
    before it -- the Python `break`s the outer loop after setting `target_fq`."""
    native, py = _xfile_both(tmp_path, {
        "models.py": "class Thing:\n    pass\n",
        "views.py": (
            "from .models import Thing\n"
            "class View:\n"
            "    def get(self):\n"
            "        return Thing()\n"
        ),
    })
    assert _canon(native) == _canon(py)
    assert any(e["relation"] == "uses" for e in native), "expected a cross-file uses edge"


def test_aliased_import_attributes_to_the_local_name(tmp_path):
    """`from m import A as B` resolves the target through A but the body
    references B, so `refs` must be keyed on the LOCAL name."""
    native, py = _xfile_both(tmp_path, {
        "m.py": "class Alpha:\n    pass\n",
        "u.py": (
            "from .m import Alpha as Beta\n"
            "def use():\n"
            "    return Beta()\n"
        ),
    })
    assert _canon(native) == _canon(py)
    assert any(e["relation"] == "uses" for e in native), "the alias reference was lost"


def test_reference_line_is_the_first_occurrence(tmp_path):
    """`ref_sources` uses `setdefault`, so the FIRST line a symbol references the
    name wins. Emitting the last would move every such edge's source_location."""
    native, py = _xfile_both(tmp_path, {
        "m.py": "class Alpha:\n    pass\n",
        "u.py": (
            "from .m import Alpha\n"
            "def use():\n"
            "    x = Alpha()\n"
            "    y = Alpha()\n"
            "    return x, y\n"
        ),
    })
    assert _canon(native) == _canon(py)
    locs = {e["source_location"] for e in native if e["relation"] == "uses"}
    assert locs == {"L3"}, f"expected the first reference line only, got {locs}"


# ── symbol-resolution fact fusion (`py_symbol_facts`) ────────────────────────

def _facts_both(tmp_path, files: dict[str, str], target: str):
    """(native, python) `(facts, deferred)` for one file of a small package."""
    from graphify.extractors.kernel import py_facts_from_native
    from graphify.extractors.resolution import _collect_python_facts_one_file

    for name, body in files.items():
        p = tmp_path / name
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(body)
    path = tmp_path / target
    result = extract_python(path)
    payload = result.get("py_symbol_facts")
    assert payload is not None, "no py_symbol_facts payload; this test proves nothing"
    native = py_facts_from_native(path, tmp_path, payload)
    assert native is not None, "the converter deferred; this test proves nothing"
    with _seam_disabled():
        py = _collect_python_facts_one_file(path, tmp_path)
    return native, py


def _facts_repr(pair):
    facts, deferred = pair
    out = {}
    for bucket in ("imports", "exports", "uses", "module_imports", "declarations",
                   "aliases", "star_exports", "namespace_exports"):
        for obj, tag in ((facts, "f"), (deferred, "d")):
            v = getattr(obj, bucket, None)
            if v:
                out[f"{tag}.{bucket}"] = [_canon(x) for x in v]
    return _canon(out)


def test_symbol_facts_imports_and_uses_match(tmp_path):
    native, py = _facts_both(tmp_path, {
        "m.py": "class Alpha:\n    pass\n\ndef helper():\n    pass\n",
        "u.py": (
            "from .m import Alpha, helper as h\n"
            "def top():\n"
            "    h()\n"
            "    return Alpha()\n"
            "class C:\n"
            "    def method(self):\n"
            "        return helper()\n"
        ),
    }, "u.py")
    assert _facts_repr(native) == _facts_repr(py)
    facts, _ = native
    assert facts.imports, "no import facts produced"
    assert facts.uses, "no use facts produced"
    assert all("method" not in u.source_id for u in facts.uses), (
        "only TOP-LEVEL function bodies contribute uses; a method's calls must not"
    )


def test_submodule_redirect_matches(tmp_path):
    """#1146: `from pkg import submod` where the target is a package and the
    imported name is a real submodule file redirects to that FILE, not the
    package. The probe is `is_file()`, so it stays in Python -- this checks the
    split lands the fact in `module_imports` on both paths."""
    native, py = _facts_both(tmp_path, {
        "pkg/__init__.py": "",
        "pkg/submod.py": "def go():\n    pass\n",
        "u.py": "from .pkg import submod\ndef top():\n    return submod\n",
    }, "u.py")
    assert _facts_repr(native) == _facts_repr(py)
    facts, _ = native
    assert facts.module_imports, (
        "the submodule redirect produced nothing, so this test would pass with the "
        "redirect removed"
    )


def test_init_py_also_produces_exports(tmp_path):
    """An `__init__.py` re-export contributes BOTH an import and an export fact."""
    native, py = _facts_both(tmp_path, {
        "p/__init__.py": "from .inner import Thing\n",
        "p/inner.py": "class Thing:\n    pass\n",
    }, "p/__init__.py")
    assert _facts_repr(native) == _facts_repr(py)
    facts, _ = native
    assert facts.exports, "an __init__.py re-export must produce an export fact"


def test_dotted_relative_level_matches(tmp_path):
    """`level` is the leading-dot count and selects the base directory; getting it
    wrong retargets every relative import in a package."""
    native, py = _facts_both(tmp_path, {
        "a/__init__.py": "",
        "a/m.py": "class Thing:\n    pass\n",
        "a/b/__init__.py": "",
        "a/b/u.py": "from ..m import Thing\ndef top():\n    return Thing()\n",
    }, "a/b/u.py")
    assert _facts_repr(native) == _facts_repr(py)
    facts, _ = native
    assert facts.imports, "the two-dot relative import resolved to nothing"


def test_subscript_annotation_visits_the_value_twice(tmp_path):
    """`np.recarray[Any, Any]` -- a subscript annotation, which no corpus in the
    gate set contains in a parameter position.

    `_python_collect_type_refs`' subscript arm reads
    `if c is value or not c.is_named: continue`, and `c is value` is ALWAYS FALSE:
    py-tree-sitter returns a fresh Node wrapper per access, so the object from
    `child_by_field_name("value")` is never the same OBJECT as the one from
    `children`, though `==` and `.id` both say they are the same node. The value is
    therefore visited a SECOND time with `generic=True`, and the annotation emits
    both a `parameter_type` and a `generic_arg` reference to it.

    The correct-looking translation -- comparing `.id()` -- drops that second visit
    and changes the context on the surviving edge after dedup. It went unnoticed
    across 3,284 files of walker parity and was found only when superset was added
    as a corpus, on 11 edges.
    """
    native, py = _both(tmp_path, (
        "import numpy as np\n"
        "from typing import Any\n"
        "class C:\n"
        "    def go(self, rows: np.recarray[Any, Any]) -> None:\n"
        "        pass\n"
    ))
    assert _canon(native) == _canon(py)
    ctxs = sorted(e.get("context") for e in native["edges"]
                  if e["relation"] == "references")
    assert "generic_arg" in ctxs and "parameter_type" in ctxs, (
        f"expected BOTH contexts from the double visit, got {ctxs}"
    )
