"""Constructs the corpora cannot reach, pinned against the pure-Python extractor.

`harness/kernel_walker_parity.py` and `harness/kernel_python_e2e_parity.py` compare
the native Python walker against `_extract_generic` / `extract_python` over 3,283
real files, which is the primary evidence. But a corpus only exercises what it
happens to contain, and an injection sweep found one branch it cannot reach at all:
django has 165 auto-generated files and NOT ONE of them has a module docstring long
enough to emit, so disabling `_is_autogenerated_python` in the kernel changed
nothing and the parity run passed. A branch that no corpus can reach needs a test
or it is not covered, whatever the file count says.

Each test compares the two implementations on one source. `GRAPHIFY_KERNEL` is read
once at import, so the arms are switched by calling the walker directly rather than
by re-importing.
"""
from __future__ import annotations

import contextlib
import json

import pytest

from graphify.extract import _PYTHON_CONFIG, extract_python
from graphify.extractors import kernel as kseam
from graphify.extractors.engine import _extract_generic

kernel = pytest.importorskip("graphify_kernel", reason="native kernel not built")


def _canon(o) -> str:
    return json.dumps(o, sort_keys=True, ensure_ascii=False,
                      separators=(",", ":"), default=str)


@contextlib.contextmanager
def _seam_disabled():
    """Make `_extract_generic` take the pure-Python path for the control arm.

    Without this the control IS the kernel: `_extract_generic` calls
    `kernel.try_extract` at its top, so once `python` is in `supported_languages()`
    both arms are native and every test passes vacuously. Caught here by tests that
    failed for an unrelated-looking reason; the same trap is documented at point (1)
    of `harness/kernel_walker_parity.py`.
    """
    original = kseam.try_extract
    kseam.try_extract = lambda *a, **kw: None
    try:
        yield
    finally:
        kseam.try_extract = original


def _both(tmp_path, source: str, name: str = "m.py"):
    """(native, python) results for one source, as `extract_python` would produce.

    The Python arm is built by hand rather than by toggling `GRAPHIFY_KERNEL`: the
    kernel's load state is cached for the process, so a test that flipped the env
    var would depend on import order.
    """
    p = tmp_path / name
    p.write_text(source)
    native, reason = kernel.extract_file(
        str(p), p.read_bytes(), "python",
        kseam._import_resolver(str(p)), kseam._module_resolver(str(p)),
        kseam._py_import_resolver(str(p)),
    )
    assert native is not None, f"kernel deferred ({reason}); this test proves nothing"
    # Mirror extract_python's tail so rationale nodes are included on both sides.
    from graphify.extract import _apply_python_rationale_native, _extract_python_rationale
    items = native.pop("py_rationale", None)
    assert items is not None, "rationale payload deferred; this test proves nothing"
    _apply_python_rationale_native(p, native, items)

    with _seam_disabled():
        py = _extract_generic(p, _PYTHON_CONFIG)
        _extract_python_rationale(p, py, None)
    return native, py


AUTOGENERATED_WITH_DOCSTRING = '''\
"""This module holds the revision identifiers used by the migration runner."""
# DO NOT EDIT

revision = "a1b2c3"
down_revision = "000000"


def upgrade():
    """Apply the schema change described by this revision identifier."""
    pass
'''


def test_autogenerated_module_docstring_is_suppressed(tmp_path):
    """The branch no corpus reaches: auto-generated AND a long module docstring.

    `_is_autogenerated_python` must suppress the MODULE docstring (a revision
    annotation, not rationale) while leaving the function docstring alone. Getting
    this wrong adds a rationale node to every generated file in a repo.
    """
    native, py = _both(tmp_path, AUTOGENERATED_WITH_DOCSTRING)
    assert _canon(native) == _canon(py)
    labels = [n["label"] for n in native["nodes"] if n.get("file_type") == "rationale"]
    assert any("Apply the schema change" in l for l in labels), (
        "the function docstring should still be emitted; if it is not, this test "
        "would pass even with the suppression removed"
    )
    assert not any("revision identifiers" in l for l in labels), (
        "the module docstring of an auto-generated file must be suppressed"
    )


@pytest.mark.parametrize("marker", [
    '"""Doc."""\n# DO NOT EDIT\n',
    '"""Doc."""\n# @generated by something\n',
    '"""Doc."""\n# Generated by the protocol buffer compiler.\n',
    '"""Doc."""\nclass Migration(migrations.Migration):\n    operations = []\n',
])
def test_each_autogenerated_marker_agrees(tmp_path, marker):
    """One case per marker in `_is_autogenerated_python`, since they are separate
    conditions and a single fixture would leave three of them untested."""
    source = (
        '"""A module docstring long enough to clear the twenty-character gate."""\n'
        + marker.split("\n", 1)[1]
    )
    native, py = _both(tmp_path, source)
    assert _canon(native) == _canon(py)


def test_docstring_exactly_at_the_length_gate(tmp_path):
    """`len(text) > 20` counts CHARACTERS. A 20-char docstring is NOT emitted and a
    21-char one is; an off-by-one here silently changes every borderline file."""
    for n, expect in ((20, False), (21, True)):
        native, py = _both(tmp_path, f'"""{"x" * n}"""\n', name=f"g{n}.py")
        assert _canon(native) == _canon(py)
        got = any(x.get("file_type") == "rationale" for x in native["nodes"])
        assert got is expect, f"{n} chars: emitted={got}, expected {expect}"


def test_non_ascii_docstring_body(tmp_path):
    """The id recipe defers on non-ASCII, but a docstring's TEXT is only ever a
    label -- it must not defer, and the label is built by the same Python helper on
    both paths."""
    native, py = _both(tmp_path, '"""Ünïcödé rationale text that is quite long."""\n')
    assert _canon(native) == _canon(py)


def test_form_feed_defers_the_rationale_payload_only(tmp_path):
    """A form feed is a `str.splitlines()` break that Rust's `.lines()` misses, so
    every rationale line number after it would shift. The payload must defer -- and
    the nodes/edges must still come from the kernel, since the two are separate
    axes."""
    p = tmp_path / "ff.py"
    p.write_text('def a():\n    pass\n\x0c\n# NOTE: after the page break\n')
    native, reason = kernel.extract_file(
        str(p), p.read_bytes(), "python",
        kseam._import_resolver(str(p)), kseam._module_resolver(str(p)),
        kseam._py_import_resolver(str(p)),
    )
    assert native is not None, f"the whole file must not defer, only its rationale ({reason})"
    assert "py_rationale" not in native, "the rationale payload must defer on a form feed"
    # And the end-to-end result must still match, via the Python fallback.
    assert _canon(extract_python(p)) == _canon(_fallback(p))


def _fallback(p):
    from graphify.extract import _extract_python_rationale
    with _seam_disabled():
        py = _extract_generic(p, _PYTHON_CONFIG)
        _extract_python_rationale(p, py, None)
    return py


def test_relative_import_resolution_matches(tmp_path):
    """The relative-import branch is the one place the walker calls back into
    Python, and it decides an edge TARGET. A package directory must resolve to its
    `__init__.py`, not to a nonexistent `pkg.py` (#2455)."""
    (tmp_path / "pkg").mkdir()
    (tmp_path / "pkg" / "__init__.py").write_text("value = 1\n")
    native, py = _both(tmp_path, "from .pkg import value\nfrom .missing import other\n")
    assert _canon(native) == _canon(py)
    targets = {e["target"]: e for e in native["edges"] if e["relation"] == "imports_from"}
    assert any("target_file" in e for e in targets.values()), (
        "the resolvable import should be stamped with its target file"
    )
    assert any("target_file" not in e for e in targets.values()), (
        "the unresolvable one must stay dangling, not be stamped speculatively"
    )
