//! `_extract_python_rationale`, as a SEPARATE side channel.
//!
//! # Why this is in the kernel at all
//!
//! `extract_python` is `_extract_generic` followed by `_extract_python_rationale`,
//! and the two used to parse the file twice. Commit 233420a fixed that by handing
//! the structural parse to the rationale pass through `parsed_out` -- but a file
//! the kernel handles returns BEFORE that parse, so `parsed` is empty and the
//! rationale pass parses again. Routing Python natively without this module would
//! hand back the fusion and cost roughly a third of the win.
//!
//! # Why the LABELS are still built in Python
//!
//! `_shorten_rationale_label` calls `textwrap.shorten`, which is
//! `TextWrapper(max_lines=1).fill()` -- whitespace collapsing, a word-boundary
//! cut, a hyphen/em-dash splitting regex and a placeholder fallback. Reproducing
//! it byte-exactly in Rust is a large surface whose failures would be silent and
//! cosmetic-looking (a label truncated one word early), and it is not where the
//! time goes: the parse is. So the kernel emits the RAW text plus the line and
//! owner id, and `_apply_python_rationale_native` builds the rows with the same
//! `_shorten_rationale_label` and `_make_id` the Python path uses.
//!
//! # Why the payload can defer on its own
//!
//! Like `js_symbol_facts`, this is a separate deferral axis: omitting the key
//! makes `extract_python` run the Python rationale pass for that file alone,
//! while its nodes and edges still come from the native walk. Coupling the two
//! would let a gap in either cost the speedup of both.

use pyo3::prelude::*;
use pyo3::types::{PyDict, PyList};
use tree_sitter::Node;

use crate::ids::make_id_ascii;
use crate::js::ast::children;
use super::{Ctx, R};

/// Characters `str.splitlines()` breaks on that Rust's `.lines()` does not.
///
/// The comment scan below is line-numbered by `enumerate(source_text.splitlines())`,
/// so a single form feed -- legal in Python source and used as an Emacs page
/// break -- would shift every subsequent rationale node's line by one. Rather than
/// reimplement `splitlines`, a file containing any of these defers the payload.
const EXOTIC_LINE_BREAKS: &[char] = &[
    '\x0b', '\x0c', '\x1c', '\x1d', '\x1e', '\u{85}', '\u{2028}', '\u{2029}',
];

/// `_RATIONALE_PREFIXES`.
const RATIONALE_PREFIXES: &[&str] = &[
    "# NOTE:", "# IMPORTANT:", "# HACK:", "# WHY:", "# RATIONALE:", "# TODO:", "# FIXME:",
];

/// Python's `str.strip()` -- see `imports::py_strip` for why this is not `trim`.
fn py_strip(s: &str) -> &str {
    s.trim_matches(|c| {
        matches!(c, ' ' | '\t' | '\n' | '\r' | '\x0b' | '\x0c')
            || matches!(c, '\x1c' | '\x1d' | '\x1e' | '\x1f')
    })
}

/// `text.strip("\"'").strip('\"\"\"').strip("'''").strip()`.
///
/// Python's `str.strip(chars)` trims any character in the SET, so `.strip('\"\"\"')`
/// is `.strip('\"')` and the second and third calls are no-ops after the first.
/// The sequence still matters: quotes come off before whitespace, so
/// `'''  "quoted"  '''` keeps its inner quotes (the outer characters are spaces,
/// which the quote-strip does not touch) and only loses them to the final
/// whitespace trim.
fn strip_docstring(s: &str) -> &str {
    let s = s.trim_matches(|c| c == '"' || c == '\'');
    py_strip(s)
}

/// `_get_docstring(body_node)`: the first statement of a body, if it is a string
/// expression of more than 20 characters.
///
/// The `break` after the first child is Python's, not an oversight -- only the
/// FIRST statement can be a docstring.
fn get_docstring<'a>(ctx: &Ctx<'a, '_>, body: Option<Node>) -> R<Option<(String, usize)>> {
    let Some(body) = body else { return Ok(None) };
    for child in children(body) {
        if child.kind() == "expression_statement" {
            for sub in children(child) {
                if matches!(sub.kind(), "string" | "concatenated_string") {
                    let text = strip_docstring(ctx.text(sub)?);
                    // `len(text) > 20` counts CHARACTERS, not bytes.
                    if text.chars().count() > 20 {
                        return Ok(Some((
                            text.to_string(),
                            child.start_position().row + 1,
                        )));
                    }
                }
            }
        }
        break;
    }
    Ok(None)
}

/// One `_add_rationale(text, line, parent_nid)` call, in emission order.
pub struct Item {
    text: String,
    line: usize,
    parent_nid: String,
}

/// `_is_autogenerated_python(source)`, over the first 2048 BYTES.
///
/// Python decodes that slice with `errors="replace"`, so a multi-byte character
/// straddling the boundary becomes U+FFFD on both sides; the markers below are all
/// ASCII, so a replacement character can never create or destroy a match.
fn is_autogenerated(source: &[u8]) -> bool {
    let head = String::from_utf8_lossy(&source[..source.len().min(2048)]);
    if head.contains("DO NOT EDIT")
        || head.contains("@generated")
        || head.contains("Generated by the protocol buffer")
    {
        return true;
    }
    // `re.search(r"^revision\s*[:=]", head, re.MULTILINE)`. Written out rather than
    // pulled in as a regex dependency: it is one anchored literal followed by
    // optional whitespace and one of two characters.
    let revision = head.split('\n').any(|line| {
        let rest = match line.strip_prefix("revision") {
            Some(r) => r,
            None => return false,
        };
        let rest = rest.trim_start_matches(|c: char| c.is_whitespace());
        rest.starts_with(':') || rest.starts_with('=')
    });
    if revision && head.contains("def upgrade(") && head.contains("down_revision") {
        return true;
    }
    head.contains("class Migration(migrations.Migration)") && head.contains("operations")
}

/// `walk_docstrings(node, parent_nid)`.
fn walk_docstrings(
    ctx: &Ctx,
    node: Node,
    parent_nid: &str,
    stem: &str,
    file_nid: &str,
    out: &mut Vec<Item>,
) -> R<()> {
    match node.kind() {
        "class_definition" => {
            let name_node = node.child_by_field_name("name");
            let body = node.child_by_field_name("body");
            if let (Some(name_node), Some(body)) = (name_node, body) {
                let class_name = ctx.text(name_node)?;
                let nid = make_id_ascii(&[stem, class_name]).ok_or("non_ascii_id")?;
                if let Some((text, line)) = get_docstring(ctx, Some(body))? {
                    out.push(Item { text, line, parent_nid: nid.clone() });
                }
                for child in children(body) {
                    walk_docstrings(ctx, child, &nid, stem, file_nid, out)?;
                }
            }
            Ok(())
        }
        "function_definition" => {
            let name_node = node.child_by_field_name("name");
            let body = node.child_by_field_name("body");
            if let (Some(name_node), Some(body)) = (name_node, body) {
                let func_name = ctx.text(name_node)?;
                let nid = if parent_nid != file_nid {
                    make_id_ascii(&[parent_nid, func_name])
                } else {
                    make_id_ascii(&[stem, func_name])
                }
                .ok_or("non_ascii_id")?;
                if let Some((text, line)) = get_docstring(ctx, Some(body))? {
                    out.push(Item { text, line, parent_nid: nid });
                }
            }
            // Deliberately does NOT recurse: a nested `def`'s docstring is not
            // collected, exactly as in Python.
            Ok(())
        }
        _ => {
            for child in children(node) {
                walk_docstrings(ctx, child, parent_nid, stem, file_nid, out)?;
            }
            Ok(())
        }
    }
}

/// Collect every `_add_rationale` call the Python pass would make, in order:
/// the module docstring, then class/function docstrings, then rationale comments.
pub fn collect(ctx: &Ctx, root: Node) -> R<Vec<Item>> {
    let text = std::str::from_utf8(ctx.src).map_err(|_| "source_not_utf8")?;
    if text.contains(EXOTIC_LINE_BREAKS) {
        return Err("exotic_line_break");
    }
    let mut out: Vec<Item> = Vec::new();
    let stem = ctx.stem.clone();
    let file_nid = ctx.file_nid.clone();

    if !is_autogenerated(ctx.src) {
        if let Some((text, line)) = get_docstring(ctx, Some(root))? {
            out.push(Item { text, line, parent_nid: file_nid.clone() });
        }
    }
    walk_docstrings(ctx, root, &file_nid, &stem, &file_nid, &mut out)?;

    // Rationale comments. Python enumerates `source_text.splitlines()` from 1;
    // the exotic-break guard above is what makes `split('\n')` equivalent, except
    // that `splitlines()` does not yield a final empty element for a trailing
    // newline. Nothing after the last newline can match a prefix, so dropping it
    // is safe -- but it is dropped explicitly rather than left to chance.
    let mut lines: Vec<&str> = text.split('\n').collect();
    if text.ends_with('\n') {
        lines.pop();
    }
    for (i, line_text) in lines.iter().enumerate() {
        // `splitlines()` also strips a `\r` that `split('\n')` leaves behind.
        let line_text = line_text.strip_suffix('\r').unwrap_or(line_text);
        let stripped = py_strip(line_text);
        if RATIONALE_PREFIXES.iter().any(|p| stripped.starts_with(p)) {
            out.push(Item {
                text: stripped.to_string(),
                line: i + 1,
                parent_nid: file_nid.clone(),
            });
        }
    }
    Ok(out)
}

/// `[(text, line, parent_nid), ...]` -- raw material, not rows. See the module
/// docstring for why the label and the id are minted on the Python side.
pub fn to_py<'py>(py: Python<'py>, items: &[Item]) -> PyResult<Bound<'py, PyList>> {
    let out = PyList::empty(py);
    for it in items {
        let row = PyDict::new(py);
        row.set_item("text", &it.text)?;
        row.set_item("line", it.line)?;
        row.set_item("parent_nid", &it.parent_nid)?;
        out.append(row)?;
    }
    Ok(out)
}
